blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/invite/WDzuyqVwTX
    about: Ask a question on our official Discord!
  - name: Trello
    url: https://trello.com/w/calculusgames
    about: View planned information on our Trello Bug