name: Fetaure Request
description: Request a new addition.
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out a suggestion.

  - type: dropdown
    attributes:
      label: Addition Type
      description: What are we adding?
      multiple: false
      options:
        - Official Kotlin Library
        - 3rd Party Library
    validations:
      required: true

  - type: input
    attributes:
      label: Repository Link
      placeholder: |
        Ex: "https://github.com/myfavoritedev/cool-library"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information you would like to provide.
    validations:
      required: false